language: go

#omitting this line fails build bc it tries to use TLS1.0
# which bitbucket blocks so a clone will not go through
dist: xenial

# Force-enable Go modules. This will be unnecessary when Go 1.12 lands.
env:
  - GO111MODULE=on

# You don't need to test on very old version of the Go compiler. It's the user's
# responsibility to keep their compilers up to date.
go:
  - 1.11.x

# Only clone the most recent commit.
git:
  depth: 1

# Skip the install step. Don't `go get` dependencies. Only build with the code
# in vendor/
install: true

# email me results if a test fails.
notifications:
    recipients:
        - ddmoorish@gmail.com
        on_success: never
        on_failure: always
script:
  - go test -v ./...
