apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-provenance-apiserver
  namespace: provenance
  labels:
    apiserver: "true"
spec:
  replicas: 1
  selector:
    apiserver: "true"
  template:
    metadata:
      labels:
        apiserver: "true"
    spec:
      serviceAccountName: apiserver
      containers:
      - name: kube-provenance-apiserver
        image: kube-provenance-apiserver:latest
        imagePullPolicy: Never
        command: [ "/kube-provenance-apiserver", "--etcd-servers=http://localhost:2379" ]
        volumeMounts:
        - name: kind-compositions-volume
          mountPath: /etc/kubeprovenance
        - mountPath: /tmp/kube-apiserver-audit.log
          name: audit-log
        env:
        - name: KIND_COMPOSITION_FILE
          value: /etc/kubeprovenance/kind_compositions.yaml
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
      - name: etcd
        image: quay.io/coreos/etcd:v3.2.18
      volumes:
        - name: kind-compositions-volume
          configMap:
            name: kind-compositions-config-map
        - name: audit-log
          hostPath:
            path: /tmp/kube-apiserver-audit.log
            type: FileOrCreate
